package com.example.constructionmis.models;

import jakarta.persistence.*;
import java.sql.Timestamp;

/**
 * Represents a tasks assigned in the Construction MIS application.
 *
 * <p>
 *  tasks can be assigned by different users such as ADMIN, PROJECT_MANAGER, or ENGINEER
 * </p>
 * <p>
 *      * This entity is mapped to the {@code tasks} table in the database.
 * </p>
 */
@Entity
@Table(name = "tasks")
public class Task {

    /**
     * this is a unique identifier of the task
     * it is automatically generated by the database
     */

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * this is the name of the task to be performed
     * it can never be null
     */

    @Column(name = "task_name", nullable = false)
    private String taskName;

    @Column(length = 200)
    private String description;

    @Column(nullable = false)
    private String status; // PENDING | IN_PROGRESS | COMPLETED

    @Column(name = "start_date")
    private Timestamp startDate;

    @Column(name = "end_date")
    private Timestamp endDate;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Timestamp createdAt;

    // Relationships

    @ManyToOne
    @JoinColumn(name = "assigned_to", nullable = false)
    private User assignedTo; // the engineer/user assigned to this task

    @ManyToOne
    @JoinColumn(name = "project_id", nullable = false)
    private Project project; // the project this task belongs to

    // Constructors

    public Task() {
        // Required by Hibernate
    }

    public Task(String taskName, String description, String status, User assignedTo, Project project) {
        this.taskName = taskName;
        this.description = description;
        this.status = status;
        this.assignedTo = assignedTo;
        this.project = project;
    }

    // Automatically set createdAt timestamp
    @PrePersist
    protected void onCreate() {
        this.createdAt = new Timestamp(System.currentTimeMillis());
    }

    // Getters and Setters

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTaskName() {
        return taskName;
    }

    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Timestamp getStartDate() {
        return startDate;
    }

    public void setStartDate(Timestamp startDate) {
        this.startDate = startDate;
    }

    public Timestamp getEndDate() {
        return endDate;
    }

    public void setEndDate(Timestamp endDate) {
        this.endDate = endDate;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public User getAssignedTo() {
        return assignedTo;
    }

    public void setAssignedTo(User assignedTo) {
        this.assignedTo = assignedTo;
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    @Override
    public String toString() {
        return "Task{" +
                "id=" + id +
                ", taskName='" + taskName + '\'' +
                ", description='" + description + '\'' +
                ", status='" + status + '\'' +
                ", startDate=" + startDate +
                ", endDate=" + endDate +
                ", createdAt=" + createdAt +
                ", assignedTo=" + assignedTo.getFullName() +
                ", project=" + project.getProjectName() +
                '}';
    }
}
