package com.example.constructionmis.models;

import jakarta.persistence.*;
import java.sql.Timestamp;
import java.util.*;

/**
 * Represents a system user in the Construction MIS application.
 *
 * <p>
 * A user can have different roles such as ADMIN, PROJECT_MANAGER, or ENGINEER.
 * Users can create projects, be assigned tasks, report delays, and generate
 * reports.
 * </p>
 *
 * <p>
 * This entity is mapped to the {@code users} table in the database.
 * </p>
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * Unique identifier for the user.
     * This value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * Full name of the user.
     * This field cannot be null.
     */
    @Column(name = "full_name", nullable = false)
    private String fullName;

    /**
     * Email address of the user.
     * This value must be unique and cannot be null.
     */
    @Column(unique = true, nullable = false)
    private String email;

    /**
     * Hashed password of the user.
     * Passwords should never be stored in plain text.
     */
    @Column(nullable = false)
    private String password;

    /**
     * Role of the user in the system.
     * Examples: ADMIN, PROJECT_MANAGER, ENGINEER.
     */
    @Column(nullable = false)
    private String role;

    /**
     * Timestamp indicating when the user account was created.
     */
    @Column(name = "created_at")
    private Timestamp createdAt;

    /**
     * Projects created by this user.
     */
    @OneToMany(mappedBy = "createdBy")
    private List<Project> projectsCreated = new ArrayList<>();

    /**
     * Tasks assigned to this user.
     */
    @OneToMany(mappedBy = "assignedTo")
    private List<Task> tasksAssigned = new ArrayList<>();

    /**
     * Delays reported by this user.
     */
    @OneToMany(mappedBy = "reportedBy")
    private List<Delay> delaysReported = new ArrayList<>();

    /**
     * Reports generated by this user.
     */
    @OneToMany(mappedBy = "generatedBy")
    private List<Report> reportsGenerated = new ArrayList<>();

    @Column(name = "otp")
    private String otp;

    @Column(name = "is_verified", nullable = false)
    private boolean isVerified = false;

    /**
     * No-argument constructor required by JPA.
     */
    public User() {
    }

    /**
     * Creates a fully initialized User object.
     *
     * @param id               the user ID
     * @param fullName         the full name of the user
     * @param email            the user's email address
     * @param password         the hashed password
     * @param role             the role of the user
     * @param createdAt        the account creation timestamp
     * @param projectsCreated  list of projects created by the user
     * @param tasksAssigned    list of tasks assigned to the user
     * @param delaysReported   list of delays reported by the user
     * @param reportsGenerated list of reports generated by the user
     */
    public User(
            int id,
            String fullName,
            String email,
            String password,
            String role,
            Timestamp createdAt,
            List<Project> projectsCreated,
            List<Task> tasksAssigned,
            List<Delay> delaysReported,
            List<Report> reportsGenerated) {
        this.id = id;
        this.fullName = fullName;
        this.email = email;
        this.password = password;
        this.role = role;
        this.createdAt = createdAt;
        this.projectsCreated = projectsCreated;
        this.tasksAssigned = tasksAssigned;
        this.delaysReported = delaysReported;
        this.reportsGenerated = reportsGenerated;
    }

    /**
     * Automatically sets the creation timestamp before the entity is persisted.
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = new Timestamp(System.currentTimeMillis());
    }

    /**
     * @return the user ID
     */
    public int getId() {
        return id;
    }

    /**
     * @param id sets the user ID
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return the user's full name,firstName and lastName
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * @param fullName sets the user's full name
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * @return the user's email address
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email sets the user's email address
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return the hashed password
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param password sets the hashed password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * @return the user's role
     */
    public String getRole() {
        return role;
    }

    /**
     * @param role sets the user's role
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * @return account creation timestamp
     */
    public Timestamp getCreatedAt() {
        return createdAt;
    }

    /**
     * @param createdAt sets the creation timestamp
     */
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * @return list of projects created by the user
     */
    public List<Project> getProjectsCreated() {
        return projectsCreated;
    }

    public void setProjectsCreated(List<Project> projectsCreated) {
        this.projectsCreated = projectsCreated;
    }

    /**
     * @return list of tasks assigned to the user
     */
    public List<Task> getTasksAssigned() {
        return tasksAssigned;
    }

    public void setTasksAssigned(List<Task> tasksAssigned) {
        this.tasksAssigned = tasksAssigned;
    }

    /**
     * @return list of delays reported by the user
     */
    public List<Delay> getDelaysReported() {
        return delaysReported;
    }

    public void setDelaysReported(List<Delay> delaysReported) {
        this.delaysReported = delaysReported;
    }

    /**
     * @return list of reports generated by the user
     */
    public List<Report> getReportsGenerated() {
        return reportsGenerated;
    }

    public void setReportsGenerated(List<Report> reportsGenerated) {
        this.reportsGenerated = reportsGenerated;
    }

    public String getOtp() {
        return otp;
    }

    public void setOtp(String otp) {
        this.otp = otp;
    }

    public boolean isVerified() {
        return isVerified;
    }

    public void setVerified(boolean verified) {
        isVerified = verified;
    }
}
