package com.example.constructionmis.daos;

import com.example.constructionmis.models.Report;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityTransaction;
import java.util.List;

public class ReportDAO {

    private final EntityManager em;

    public ReportDAO(EntityManager em) {
        this.em = em;
    }

    // CREATE
    public void save(Report report) {
        EntityTransaction tx = em.getTransaction();
        tx.begin();
        em.persist(report);
        tx.commit();
    }

    // READ
    public Report findById(int id) {
        return em.find(Report.class, id);
    }

    public List<Report> findAll() {
        return em.createQuery("FROM Report", Report.class).getResultList();
    }

    // Find reports by project ID
    public List<Report> findByProjectId(int projectId) {
        return em.createQuery("FROM Report r WHERE r.project.id = :projectId", Report.class)
                .setParameter("projectId", projectId)
                .getResultList();
    }

    // Find reports by status
    public List<Report> findByStatus(String status) {
        return em.createQuery("FROM Report r WHERE r.status = :status", Report.class)
                .setParameter("status", status)
                .getResultList();
    }

    // Find reports generated by a specific user
    public List<Report> findByGeneratedBy(int userId) {
        return em.createQuery("FROM Report r WHERE r.generatedBy.id = :userId", Report.class)
                .setParameter("userId", userId)
                .getResultList();
    }

    // UPDATE
    public void update(Report report) {
        EntityTransaction tx = em.getTransaction();
        tx.begin();
        em.merge(report);
        tx.commit();
    }

    // DELETE
    public void delete(Report report) {
        EntityTransaction tx = em.getTransaction();
        tx.begin();
        em.remove(report);
        tx.commit();
    }
}
